# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ccb76bf16d04b50269caf39a9ca023b11be911c9cb97e88db7a181720f35f29de3ecb6f1e255d3fb6685e2754613294d6b8df772c1c2b5b30437e318d1d24e7

test:
  secret_key_base: ad4da6d308b31f27370bd8aff31de50729a0d9bc9f24d419f84da76a0ab44bfa20d0f16291f28896a95734042e81cf0a71ca4e3fd746db2c073ba6b588bcf256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
